# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-18 14:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedules', '0001_initial'),
        ('reservations_status', '0001_initial'),
        ('payment_methods', '0001_initial'),
        ('courts', '0002_auto_20170418_1132'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courts', to='courts.Courts', verbose_name='courts')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='payment_methods.PaymentMethods', verbose_name='payment')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='schedules.Schedules', verbose_name='schedules')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='services.Services', verbose_name='service')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_status', to='reservations_status.ReservationsStatus', verbose_name='reservations_status')),
            ],
        ),
    ]
