# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 15:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedules', '0001_initial'),
        ('reservations_status', '0001_initial'),
        ('payment_methods', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='edition date', null=True)),
                ('createdDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='res_courts', to='courts.Courts', verbose_name='courts')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='res_payment', to='payment_methods.PaymentMethods', verbose_name='payment')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='res_schedules', to='schedules.Schedules', verbose_name='schedules')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='res_service', to='services.Services', verbose_name='service')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='res_reservationsStatus', to='reservations_status.ReservationsStatus', verbose_name='reservationsStatus')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
