# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-15 00:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations_status', '0001_initial'),
        ('schedules', '0001_initial'),
        ('services', '0001_initial'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='res_schedule', to='schedules.Schedule', verbose_name='schedule'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='res_service', to='services.Services', verbose_name='service'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='res_reservationsStatus', to='reservations_status.ReservationsStatus', verbose_name='reservationsStatus'),
        ),
    ]
