# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 16:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservations_status', '0003_auto_20170504_1310'),
        ('payment_methods', '0003_auto_20170504_1310'),
        ('schedules', '0002_auto_20170504_1310'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courts', '0003_auto_20170504_1310'),
        ('services', '0002_auto_20170504_1310'),
        ('reservations', '0002_auto_20170418_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='edition date', null=True)),
                ('createdDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='courts',
            name='client',
        ),
        migrations.RemoveField(
            model_name='courts',
            name='court',
        ),
        migrations.RemoveField(
            model_name='courts',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='courts',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='courts',
            name='service',
        ),
        migrations.RemoveField(
            model_name='courts',
            name='status',
        ),
        migrations.DeleteModel(
            name='Courts',
        ),
        migrations.AddField(
            model_name='reservations',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courts', to='courts.Courts', verbose_name='courts'),
        ),
        migrations.AddField(
            model_name='reservations',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='payment_methods.PaymentMethods', verbose_name='payment'),
        ),
        migrations.AddField(
            model_name='reservations',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='schedules.Schedules', verbose_name='schedules'),
        ),
        migrations.AddField(
            model_name='reservations',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='services.Services', verbose_name='service'),
        ),
        migrations.AddField(
            model_name='reservations',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_status', to='reservations_status.ReservationsStatus', verbose_name='reservations_status'),
        ),
    ]
