# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-31 00:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        ('reservations', '0003_reservation_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club_name', to='clubs.Clubs'),
        ),
    ]
