# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_auto_20170504_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='res_courts', to='courts.Courts', verbose_name='courts'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='res_payment', to='payment_methods.PaymentMethods', verbose_name='payment'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='res_schedules', to='schedules.Schedules', verbose_name='schedules'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='res_service', to='services.Services', verbose_name='service'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='res_reservationsStatus', to='reservations_status.ReservationsStatus', verbose_name='reservationsStatus'),
        ),
    ]
