# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourtStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='edition date', null=True)),
                ('status', models.PositiveIntegerField(choices=[(1, 'No Disponible'), (0, 'Disponible'), (2, 'Reservada'), (3, 'Confirmada')], default=0, verbose_name='estado')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
