# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courts_status', '0002_auto_20170418_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtstatus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='creation date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courtstatus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='edition date', null=True),
        ),
    ]
