# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts_status', '0003_auto_20170504_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courtstatus',
            name='name',
        ),
        migrations.AddField(
            model_name='courtstatus',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'No Disponible'), (0, 'Disponible'), (2, 'Reservada'), (3, 'Confirmada')], default=0, verbose_name='status'),
        ),
    ]
