# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-11 13:48
from __future__ import unicode_literals

import ajaximage.fields
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('address', models.CharField(max_length=50, verbose_name='direccion')),
                ('description', models.TextField(verbose_name='descripcion')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('mail', models.EmailField(max_length=254)),
                ('logo', ajaximage.fields.AjaxImageField(verbose_name='image')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='latitud')),
                ('length', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='longitud')),
            ],
        ),
    ]
