# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-14 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubs',
            name='address',
            field=models.CharField(max_length=50, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=20, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='length',
            field=models.DecimalField(decimal_places=6, max_digits=20, verbose_name='length'),
        ),
    ]
