# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-08 16:09
from __future__ import unicode_literals

import ajaximage.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recinto',
            fields=[
                ('id_recinto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('direccion', models.CharField(max_length=50, verbose_name='dirección')),
                ('descripcion', models.TextField(verbose_name='descripción')),
                ('telefono', models.DecimalField(decimal_places=0, max_digits=9, verbose_name='telefono')),
                ('correo', models.CharField(max_length=50, verbose_name='correo')),
                ('logo', ajaximage.fields.AjaxImageField(verbose_name='image')),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='latitud')),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='longitud')),
            ],
        ),
    ]
