# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='edition date', null=True)),
                ('day', models.PositiveIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Mi\xe9rcoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'S\xe1bado'), (6, 'Domingo')], verbose_name='day')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='edition date', null=True)),
                ('month', models.CharField(choices=[(b'1', b'January'), (b'2', b'February'), (b'3', b'March'), (b'4', b'April'), (b'5', b'May'), (b'6', b'June'), (b'7', b'July'), (b'8', b'August'), (b'9', b'September'), (b'10', b'October'), (b'11', b'November'), (b'12', b'December')], default='1', max_length=9)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
