# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='day',
            field=models.CharField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Mi\xe9rcoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'S\xe1bado'), (6, 'Domingo')], max_length=20, verbose_name='day'),
        ),
    ]
