# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0003_auto_20170705_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='day',
            field=models.PositiveIntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Mi\xe9rcoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'S\xe1bado'), (7, 'Domingo')], default='1'),
        ),
    ]
