# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-17 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courts_status', '0001_initial'),
        ('clubs', '0002_auto_20170414_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('number', models.CharField(max_length=50, verbose_name='number')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='court', to='clubs.Clubs', verbose_name='club')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='courts_status.Court_status', verbose_name='status')),
            ],
        ),
    ]
