# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-02 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '__first__'),
        ('courts_status', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='edition date', null=True)),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('number', models.CharField(max_length=50, verbose_name='number')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club', to='clubs.Club', verbose_name='club')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='court_status', to='courts_status.CourtStat', verbose_name='estado')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
