# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0003_auto_20170504_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courts',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='court_status', to='courts_status.CourtStatus', verbose_name='status'),
        ),
    ]
