# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-02 02:51
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='edition date', null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='price')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='court_sche', to='courts.Court', verbose_name='court')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchedulesCreate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='edition date', null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='price')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('court', models.ForeignKey(default=b'Sin asignar', on_delete=django.db.models.deletion.CASCADE, related_name='court_sche_create', to='courts.Court', verbose_name='court')),
                ('day', models.ManyToManyField(related_name='day_create', to='dates.Day', verbose_name='day')),
                ('end_time', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_time_hour', to='dates.Hour')),
                ('month', models.ManyToManyField(related_name='month_create', to='dates.Month', verbose_name='month')),
                ('start_time', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='start_time_hour', to='dates.Hour')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
