# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 00:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulescreate',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_court', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='schedulescreate',
            name='court',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='court_sche_create', to='courts.Court', verbose_name='court'),
        ),
        migrations.AlterField(
            model_name='schedulescreate',
            name='end_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_time_hour', to='dates.Hour'),
        ),
        migrations.AlterField(
            model_name='schedulescreate',
            name='start_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start_time_hour', to='dates.Hour'),
        ),
    ]
