# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-25 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulescreate',
            name='day',
            field=models.ManyToManyField(related_name='day_create', to='dates.Day', verbose_name='day'),
        ),
        migrations.AlterField(
            model_name='schedulescreate',
            name='month',
            field=models.ManyToManyField(related_name='month_create', to='dates.Month', verbose_name='month'),
        ),
    ]
