# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_day_month_schedulescreate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulescreate',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dates.Day', verbose_name='day'),
        ),
        migrations.AlterField(
            model_name='schedulescreate',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dates.Month', verbose_name='month'),
        ),
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.DeleteModel(
            name='Month',
        ),
    ]
