# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0001_initial'),
        ('schedules', '0003_auto_20170630_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulescreate',
            name='day',
        ),
        migrations.AddField(
            model_name='schedulescreate',
            name='day',
            field=models.ManyToManyField(to='dates.Day', verbose_name='day'),
        ),
        migrations.RemoveField(
            model_name='schedulescreate',
            name='month',
        ),
        migrations.AddField(
            model_name='schedulescreate',
            name='month',
            field=models.ManyToManyField(to='dates.Month', verbose_name='month'),
        ),
    ]
