# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 01:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0006_hour'),
        ('schedules', '0004_auto_20170705_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulescreate',
            name='end_time',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_time', to='dates.Hour'),
        ),
        migrations.AddField(
            model_name='schedulescreate',
            name='start_time',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='start_time', to='dates.Hour'),
        ),
    ]
