# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 01:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_auto_20170713_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulescreate',
            name='end_time',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_time_hour', to='dates.Hour'),
        ),
        migrations.AlterField(
            model_name='schedulescreate',
            name='start_time',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='start_time_hour', to='dates.Hour'),
        ),
    ]
